---
on:
  push:
    paths:
      - VERSION

jobs:
  set-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Update Readme
        uses: ./
        with:
          FILE: README.md
          PATTERN: (udondan/ver2doc\@v)[0-9.]+
          REPLACE: \${1}${VERSION}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code || git commit -m "Updates version references" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
